FROM ubuntu:22.04 AS base

# hadolint ignore=DL3005,DL3008
RUN apt-get update -qq \
    # Make sure that all security updates are installed
    && apt-get dist-upgrade -y --no-install-recommends \
    && apt-get install -y --no-install-recommends \
      python3 \
      python3-venv \
      python3-pip \
      python3-dev \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 100 \
   && update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 100

FROM base AS python_builder

ARG POETRY_VERSION=1.8.2

# hadolint ignore=DL3008
RUN apt-get update -qq \
   && apt-get install -y --no-install-recommends \
    curl \
    && apt-get autoremove -y

# install poetry
# keep this in sync with the version in pyproject.toml and Dockerfile
ENV POETRY_VERSION=$POETRY_VERSION
ENV PYTHONUNBUFFERED=1
ENV PYTHONIOENCODING="utf-8"

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN curl -sSL https://install.python-poetry.org | python
ENV PATH="/root/.local/bin:/opt/venv/bin:${PATH}"

# install dependencies
COPY . /app/

WORKDIR /app

# hadolint ignore=SC1091,DL3013
# install dependencies and build wheels
RUN python -m venv /opt/venv && \
  . /opt/venv/bin/activate && \
  pip install --no-cache-dir -U pip && \
  pip install --no-cache-dir wheel && \
  poetry install --no-root --no-interaction

# build the Rasa SDK wheel and install it
# hadolint ignore=SC1091,DL3013
RUN poetry build -f wheel -n && \
  pip install --no-deps dist/*.whl && \
  rm -rf dist *.egg-info

RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
  && rm -rf /root/.cache/pip/*

EXPOSE 5055
ENTRYPOINT [""]