name: Pull Request Merged to Main

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  REPOSITORY: 329710836760.dkr.ecr.us-east-1.amazonaws.com/rasa-sdk-dev
  DEFAULT_PYTHON_VERSION: "3.10"

permissions:
  checks: write
  id-token: write
  pull-requests: write
  contents: read
  issues: read

jobs:
  rasa-sdk-dev-docker-image:
    name: Build Dev Docker Image and Push to AWS
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@8c3f20df09ac63af7b3ae3d7c91f105f857d8497 # v3.0.1
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
        with:
          mask-password: "true"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@0d103c3126aa41d772a8362f6aa67afac040f80c  # v3.1.0

      - name: Build and push docker image to AWS
        run: |
          IMAGE_NAME=${{ env.REPOSITORY }} \
          IMAGE_TAG=latest \
          make build-and-push-multi-platform-docker
