name: Pull Request Merged to Main

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-1
  REPOSITORY: 329710836760.dkr.ecr.eu-west-1.amazonaws.com/rasa/rasa-sdk-dev
  DEFAULT_PYTHON_VERSION: "3.10"

permissions:
  checks: write
  id-token: write
  pull-requests: write
  contents: read
  issues: read

jobs:
  rasa-sdk-dev-docker-image:
    name: Build Dev Docker Image and Push to AWS
    runs-on: ubuntu-24.04

    steps:
      - name: Check out code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@8c3f20df09ac63af7b3ae3d7c91f105f857d8497 # v3.0.1
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
        with:
          mask-password: "true"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@4574d27a4764455b42196d70a065bc6853246a25 # v3.4.0
        with:
          platforms: linux/amd64,linux/arm64
          # The latest version will lead to segmentation fault.
          image: tonistiigi/binfmt:qemu-v7.0.0-28

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca  # v3.9.0

      - name: Build and push docker image to AWS
        run: |
          IMAGE_NAME=${{ env.REPOSITORY }} \
          IMAGE_TAG=latest \
          make build-and-push-multi-platform-docker
