name: Scan Rasa SDK App Dependencies

on:
    schedule:
      # Runs at 8AM on Monday.
      - cron: '0 8 * * MON'
    workflow_dispatch:

jobs:
  get_latest_tag:
    runs-on: ubuntu-24.04

    outputs:
      tag: ${{ steps.find-tag.outputs.tag }}

    steps:
    - name: Checkout repository to check tags
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Get latest tagged release
      id: find-tag
      run: |
        git fetch --depth=1 origin "+refs/tags/*:refs/tags/*"
        echo "tag=$(git tag | sort -r -V | grep -E "^[0-9]+.[0-9]+.[0-9]+$" | head -n1)" >> $GITHUB_OUTPUT

  scan_and_alert:
    needs: get_latest_tag
    uses: RasaHQ/infrasec-workflows/.github/workflows/scan-docker-image-dependencies.yml@main
    secrets: inherit
    with:
      image_name: rasa/rasa-sdk
      image_tag: ${{ needs.get_latest_tag.outputs.tag }}
      slack_channel_id: "C070ELPSLBB"
      product_name: "Rasa SDK"